Infomaximum/platform

- build.gradle
- settings.gradle
- src/main/java/com/infomaximum/platform/control/PlatformUpgrade.java
- src/main/java/com/infomaximum/platform/sdk/component/Component.java
- src/main/java/com/infomaximum/platform/sdk/remote/excludeintegrity/ExcludeIntegrityTableService.java
- src/main/java/com/infomaximum/platform/sdk/remote/excludeintegrity/RControllerExcludeIntegrityTable.java
- src/main/java/com/infomaximum/platform/update/core/UpdateService.java
> feat: added feature to exclude tables from integrity check

- build.gradle
- settings.gradle
- src/main/java/com/infomaximum/platform/component/database/DatabaseComponent.java
- src/main/java/com/infomaximum/platform/component/database/remote/cfconfig/ColumnFamilyConfigService.java
- src/main/java/com/infomaximum/platform/component/database/remote/cfconfig/RControllerColumnFamilyConfig.java
- src/main/java/com/infomaximum/platform/component/database/remote/dbprovider/RControllerDBProviderImpl.java
- src/main/java/com/infomaximum/platform/sdk/dbprovider/ComponentDBProvider.java
- src/main/java/com/infomaximum/platform/sdk/dbprovider/RemoteDBProvider.java
- src/main/java/com/infomaximum/platform/sdk/dbprovider/remote/RControllerDBProvider.java
> feat: added feature for configuring column family options

- src/main/java/com/infomaximum/platform/sdk/remote/excludeintegrity/ExcludeIntegrityTableService.java
> feat: added feature to control list exclude tables from integrity check

- src/main/java/com/infomaximum/platform/control/PlatformStartStop.java
- src/main/java/com/infomaximum/platform/control/PlatformUpgrade.java
> fix: fixed NPE DomainObjectSource from beforeUpdate

- build.gradle
- settings.gradle
- src/main/java/com/infomaximum/platform/control/PlatformUpgrade.java
- src/main/java/com/infomaximum/platform/sdk/component/Component.java
Refs: https://jira.office.infomaximum.com/browse/PT-13819
Task: PT-13819
> feat: added caching rocksDb data schema

- src/main/java/com/infomaximum/platform/Platform.java
- src/main/java/com/infomaximum/platform/control/PlatformUpgrade.java
Refs: https://jira.office.infomaximum.com/browse/PT-14150
Task: PT-14150
> feat: fix crash before checkBeforeUpgrade and rename api

- src/main/java/com/infomaximum/platform/component/database/DatabaseComponent.java
- src/main/java/com/infomaximum/platform/component/database/DatabaseComponentExtension.java
Refs: https://jira.office.infomaximum.com/browse/PT-14118
Task: PT-14118
> feat: added method onStart in interface DatabaseComponentExtension

- src/main/java/com/infomaximum/platform/update/UpdateTask.java
- src/main/java/com/infomaximum/platform/update/util/UpdateUtil.java
- src/test/java/com/infomaximum/platform/update/util/UpdateUtilTest.java
feat: добавлена валидация версий при обновлении с учетом нового версионирования
Task: PT-14409
Refs: https://jira.office.infomaximum.com/browse/PT-14409
> feat: добавлена валидация версий при обновлении с учетом нового версионирования

- src/main/java/com/infomaximum/platform/sdk/graphql/scalartype/GraphQLScalarTypePlatform.java
> refactor: change exception for input graphQl type Duration

- src/main/java/com/infomaximum/platform/Platform.java
- src/main/java/com/infomaximum/platform/sdk/component/Component.java
- src/main/java/com/infomaximum/platform/sdk/remote/node/UpdateNodeConnectService.java
- src/main/java/com/infomaximum/platform/service/UpdateNodeConnectService.java
- src/main/java/com/infomaximum/platform/service/UpdateNodeConnectServiceImpl.java
- src/main/java/module-info.java
> feat: add UpdateNodeConnectService for node connect listeners

- src/main/java/com/infomaximum/platform/component/frontend/engine/FrontendEngine.java
> fix: disable RControllerGraphQLSubscribe if graphQl disable

- src/main/java/com/infomaximum/platform/Platform.java
- src/main/java/com/infomaximum/platform/control/PlatformStartStop.java
- src/main/java/com/infomaximum/platform/control/PlatformUpgrade.java
- src/main/java/com/infomaximum/platform/sdk/component/Component.java
- src/main/java/com/infomaximum/platform/sdk/component/ComponentEventListener.java
- src/main/java/com/infomaximum/platform/sdk/component/ComponentInfo.java
- src/main/java/com/infomaximum/platform/sdk/remote/component/ComponentEventListenerService.java
- src/main/java/com/infomaximum/platform/service/ComponentEventListenerServiceImpl.java
- src/main/java/module-info.java
> feat: add component event listener

- src/main/java/com/infomaximum/platform/component/frontend/engine/service/errorhandler/PlatformErrorHandler.java
> fix: crash with HTTP/0.9

- build.gradle
> build: update dependencies

- build.gradle
- src/main/java/com/infomaximum/platform/component/frontend/engine/FrontendEngine.java
- src/main/java/com/infomaximum/platform/component/frontend/engine/service/graphqlrequestexecute/GraphQLRequestExecuteServiceImp.java
- src/main/java/com/infomaximum/platform/sdk/exception/GeneralExceptionBuilder.java
> feat: added introspection disabled param

- src/main/java/com/infomaximum/platform/component/database/info/DBInfo.java
- src/main/java/com/infomaximum/platform/component/database/remote/info/RControllerInfo.java
- src/main/java/com/infomaximum/platform/component/database/remote/info/RControllerInfoImpl.java
- src/main/java/com/infomaximum/platform/control/PlatformStartStop.java
- src/main/java/com/infomaximum/platform/sdk/exception/GeneralExceptionBuilder.java
- src/main/java/com/infomaximum/platform/utils/JsonUtils.java
- src/main/java/module-info.java
> feat: added DBInfo in service_column_family and created RControllerInfo

- build.gradle
- src/main/java/com/infomaximum/platform/component/frontend/engine/FrontendEngine.java
- src/main/java/com/infomaximum/platform/component/frontend/engine/filter/HttpHeadersFilter.java
> feat: added HttpHeadersFilter

- src/main/java/com/infomaximum/platform/component/frontend/engine/service/graphqlrequestexecute/GraphQLRequestExecuteServiceDisable.java
- src/main/java/com/infomaximum/platform/component/frontend/engine/service/graphqlrequestexecute/GraphQLRequestExecuteServiceImp.java
> feat: added message to graphQl error

- src/main/java/com/infomaximum/platform/component/frontend/engine/service/graphqlrequestexecute/GraphQLRequestExecuteServiceImp.java
- src/main/java/com/infomaximum/platform/sdk/exception/GeneralExceptionBuilder.java
> fix: error with bad faith introspection

- build.gradle
- src/main/java/com/infomaximum/platform/component/frontend/engine/FrontendEngine.java
- src/main/java/com/infomaximum/platform/component/frontend/engine/graphql/PrepareGraphQLDocument.java
- src/main/java/com/infomaximum/platform/component/frontend/engine/service/graphqlrequestexecute/GraphQLRequestExecuteServiceImp.java
- src/main/java/com/infomaximum/platform/component/frontend/engine/service/introspection/IntrospectionChecker.java
- src/main/java/module-info.java
> feat: added IntrospectionChecker

- src/main/java/com/infomaximum/platform/component/frontend/struct/MimeType.java
- src/main/java/com/infomaximum/platform/component/frontend/utils/MimeTypeUtils.java
> feat: added MimeType.CSV

- src/main/java/com/infomaximum/platform/component/frontend/engine/controller/websocket/graphql/GraphQLController.java
- src/main/java/com/infomaximum/platform/component/frontend/engine/network/protocol/graphqltransportws/handler/graphql/GraphQLTransportWSHandler.java
> feat: added log in websocket requests

- src/main/java/com/infomaximum/platform/component/frontend/engine/controller/http/graphql/GraphQLController.java
- src/main/java/com/infomaximum/platform/sdk/exception/GeneralExceptionBuilder.java
- src/main/java/com/infomaximum/platform/utils/StringUtils.java
> fix: NegativeArraySizeException in String

- src/main/java/com/infomaximum/platform/utils/StringUtils.java
> fix: NegativeArraySizeException in String p.2
